import { useState } from 'react';
import { ArrowUpRight, ArrowRight, Check, CheckCheck, ChevronDown, FileText, FolderOpen, LayoutDashboard, ShieldCheck, CircleAlert, CircleCheck, Clock3 } from 'lucide-react';
import './portal-demo.css';

type DemoTab = 'resumen' | 'documentos' | 'preauditoria';
const documents = [
  {name:'Servicios de investigación', type:'Boleta de honorarios · N.º 52', amount:'$500.000', status:'Observado', note:'El monto de la transferencia no coincide con el valor líquido de la boleta. Se debe conciliar el comprobante.'},
  {name:'Materiales de laboratorio', type:'Factura electrónica · N.º 1842', amount:'$1.250.000', status:'Completo', note:'Factura, comprobante de pago y recepción de materiales vinculados al ítem Operación.'},
  {name:'Asistencia técnica', type:'Honorarios · N.º 108', amount:'$750.000', status:'Pendiente', note:'Falta adjuntar el informe de actividades del período antes de completar la revisión.'},
  {name:'Equipamiento del proyecto', type:'Factura electrónica · N.º 2706', amount:'$3.600.000', status:'Completo', note:'Orden de compra, factura, comprobante de pago y registro de recepción disponibles para revisión.'},
];
const observations = [
  ['01','Monto por conciliar','La transferencia asociada a la boleta N.º 52 difiere del valor líquido del documento.','Contrastar boleta, retención y comprobante bancario.'],
  ['02','Respaldo pendiente','El servicio de asistencia técnica no tiene un informe de actividades adjunto.','Solicitar el informe y vincularlo al período correspondiente.'],
  ['03','Revisar ejecución de Operación','El ítem registra un 82% de ejecución del presupuesto del ejemplo.','Revisar los gastos previstos y la disponibilidad antes de nuevas imputaciones.'],
];

export function PortalDemo() {
  const [tab, setTab] = useState<DemoTab>('resumen');
  const [filter, setFilter] = useState('Todos');
  const [expanded, setExpanded] = useState<string | null>(null);
  const [reviewed, setReviewed] = useState(false);
  const changeTab = (next: DemoTab) => {setTab(next); setExpanded(null);};
  const tabs = [['resumen','Resumen',LayoutDashboard],['documentos','Documentos',FolderOpen],['preauditoria','Preauditoría',ShieldCheck]] as const;
  return <section id="portal-demo" className="demo-section section" aria-labelledby="demo-heading"><div className="container">
    <div className="demo-heading"><div><p className="eyebrow">CONTROL QUE PUEDES VER</p><h2 id="demo-heading">Cada documento conectado.<br/><em>Cada decisión respaldada.</em></h2></div><p>Así se traduce nuestro trabajo en claridad para tu proyecto. Explora un ejemplo de seguimiento documental y presupuestario.</p></div>
    <div className="demo-window">
      <div className="demo-titlebar"><div><span className="demo-monogram">V</span><strong>VÉRITAS <span>/ VISIÓN DE PROYECTO</span></strong></div><span className="demo-badge"><span/> DEMOSTRACIÓN INTERACTIVA</span></div>
      <div className="demo-workspace"><aside className="demo-sidebar"><span className="demo-sidebar-label">ESPACIO DE TRABAJO</span><div className="demo-tabs" role="tablist" aria-label="Vistas del proyecto">{tabs.map(([id, label, Icon]) => <button key={id} role="tab" id={`demo-tab-${id}`} aria-selected={tab===id} aria-controls={`demo-panel-${id}`} tabIndex={tab===id?0:-1} className={tab===id?'demo-tab-active':''} onClick={()=>changeTab(id)} onKeyDown={(event)=>{if(['ArrowDown','ArrowRight','ArrowUp','ArrowLeft','Home','End'].includes(event.key)){event.preventDefault();const index=tabs.findIndex(([key])=>key===tab);const next=event.key==='Home'?0:event.key==='End'?2:(index+(['ArrowDown','ArrowRight'].includes(event.key)?1:2))%3;changeTab(tabs[next][0]);document.getElementById(`demo-tab-${tabs[next][0]}`)?.focus();}}}><Icon size={16}/>{label}{id==='preauditoria'&&<span>3</span>}</button>)}</div><div className="demo-sidebar-foot"><ShieldCheck size={20}/><strong>Tecnología + criterio experto</strong><p>Visibilidad en cada etapa de tu rendición.</p></div></aside>
      <div className="demo-main" id={`demo-panel-${tab}`} role="tabpanel" aria-labelledby={`demo-tab-${tab}`} tabIndex={0}>
        <div className="demo-project-heading"><div><span className="demo-project-id">PROYECTO ILUSTRATIVO · FIA</span><h3>Innovación para avanzar.</h3><p>Ejemplo de control mensual · Mes 8 de 18</p></div><span className="demo-period">MES 08 / 18</span></div>
        {tab==='resumen'&&<>
          <div className="demo-metrics"><article><span>Presupuesto aprobado</span><strong>$120.000.000</strong><small>Pesos chilenos · CLP</small></article><article><span>Presupuesto ejecutado</span><strong>$76.400.000</strong><small>63,7% del total aprobado</small></article><article className="demo-metric-highlight"><span>Gastos con respaldo completo</span><strong>171 <em>/ 184</em></strong><small><Check size={12}/> 92,9% revisados y completos</small></article></div>
          <div className="demo-overview-grid"><article className="demo-budget"><div className="demo-card-heading"><h4>Ejecución por ítem</h4><span>ETAPA 1</span></div><p>Porcentaje utilizado del presupuesto del ítem</p>{[['Recursos humanos',72.5],['Operación',82],['Equipamiento',40]].map(([name,value])=><div className="demo-progress-row" key={name}><div><span>{name}</span><strong>{String(value).replace('.',',')}%</strong></div><div className="demo-progress"><span className={value===82?'demo-progress-warning':''} style={{width:`${value}%`}}/></div></div>)}</article><article className="demo-document-status"><div className="demo-card-heading"><h4>Estado documental</h4><FolderOpen size={15}/></div><div className="demo-status-row"><span><i className="demo-dot-green"/>Completos</span><strong>171</strong></div><div className="demo-status-row"><span><i className="demo-dot-amber"/>Pendientes</span><strong>9</strong></div><div className="demo-status-row"><span><i className="demo-dot-red"/>Observados</span><strong>4</strong></div><button onClick={()=>changeTab('documentos')} className="demo-inline-button">Explorar documentos <ArrowRight size={14}/></button></article></div>
          <button className="demo-alert" onClick={()=>changeTab('preauditoria')}><CircleAlert size={18}/><span><strong>Anticiparse hace la diferencia.</strong> Hay 3 ejemplos de revisión preventiva para explorar.</span><ArrowUpRight size={17}/></button>
        </>}
        {tab==='documentos'&&<div className="demo-documents"><div className="demo-document-toolbar"><h4>Cadena de respaldo</h4><div aria-label="Filtrar documentos">{['Todos','Pendiente','Observado'].map(value=><button className={filter===value?'demo-filter-active':''} aria-pressed={filter===value} onClick={()=>{setFilter(value);setExpanded(null);}} key={value}>{value==='Todos'?value:`${value}s`}</button>)}</div></div><p className="demo-list-description">Una muestra de 4 gastos del proyecto ilustrativo. Selecciona un gasto para ver su revisión.</p>{documents.filter(doc=>filter==='Todos'||doc.status===filter).map(doc=><article className="demo-document" key={doc.name}><button onClick={()=>setExpanded(expanded===doc.name?null:doc.name)} aria-expanded={expanded===doc.name}><FileText size={18}/><span className="demo-doc-name"><strong>{doc.name}</strong><small>{doc.type}</small></span><span className="demo-doc-amount">{doc.amount}</span><span className={`demo-status-tag demo-status-${doc.status.toLowerCase()}`}>{doc.status==='Completo'?<CircleCheck size={12}/>:<Clock3 size={12}/>} {doc.status}</span><ChevronDown size={14}/></button>{expanded===doc.name&&<div className="demo-doc-detail"><ShieldCheck size={17}/><p>{doc.note}</p></div>}</article>)}</div>}
        {tab==='preauditoria'&&<div className="demo-audit"><div className="demo-document-toolbar"><h4>Revisar hoy. Rendir con claridad.</h4><span className="demo-status-tag demo-status-pendiente">3 observaciones de ejemplo</span></div><p className="demo-list-description">Esta simulación muestra cómo identificamos una brecha y proponemos el siguiente paso.</p>{observations.map(([number,title,description,action])=><article className="demo-observation" key={number}><span>{number}</span><div><h5>{title}</h5><p>{description}</p><small><ArrowRight size={12}/>{action}</small></div></article>)}<button className="demo-review-button" onClick={()=>setReviewed(!reviewed)}>{reviewed?<CheckCheck size={16}/>:<ShieldCheck size={16}/>} {reviewed?'Ejemplo revisado · Volver a explorar':'Marcar este ejemplo como revisado'}</button><p className="demo-review-status" role="status">{reviewed?'Has recorrido el ejemplo. En el servicio, nuestro equipo revisa los antecedentes de tu proyecto.':''}</p></div>}
      </div></div>
      <div className="demo-bottom"><span><span/> DATOS ILUSTRATIVOS · NO CORRESPONDEN A UN CLIENTE REAL</span><a href="#contacto">Llevemos esta claridad a tu proyecto <ArrowUpRight size={14}/></a></div>
    </div>
    <div className="demo-caption"><Check size={15}/><p>La tecnología organiza y conecta los antecedentes. El criterio de nuestros consultores guía la revisión.</p></div>
  </div></section>;
}
